### ISSUE TITLE
Category Cards Image Rendering

### ISSUE THREAD

**Issue by sameer-ah** [michael-milette/moodle-theme_gcweb#12]
When adding Category Cards by using HTML in label, images are not rendered due to some missing CSS classes.

![image](https://user-images.githubusercontent.com/36570250/126991579-04f821b0-c2e2-42a1-bd6b-cb3094d66724.png)

**Comment by michael-milette** [comment]
Hi @sameer-ah ,

Category cards are not yet part of the GCWeb theme for Moodle, only course cards. On your Moodle website, the category cards are created using static HTML code on the Front Page (i.e., Home). I am closing this issue as it is unrelated to the GCWeb theme for Moodle.

Best regards,

Michael
