### ISSUE TITLE
Main Site Heading H1

### ISSUE THREAD

**Issue by sameer-ah** [michael-milette/moodle-theme_gcweb#13]
Hi @michael-milette,

I guess it is based on guidelines from [Web Experience Toolkit (WET)](https://wet-boew.github.io/wet-boew/index-en.html), all the Government of Canada websites e.g. [canada.ca](canada.ca) , [travel.gc.ca](travel.gc.ca) etc. have main site heading as h1. We are asked to follow the same for our Moodle LMS which is using gcweb theme. Using the theme, main site heading is rendered as
![image](https://user-images.githubusercontent.com/36570250/127392371-ecadd9a2-db12-4ce8-99a9-0e291312b0be.png)

by template https://github.com/michael-milette/moodle-theme_gcweb/blob/b52c459b8507e23a0814be517e7cd19aa206c1d9/templates/header.mustache#L63-L66

Would it be possible to change it so that main site heading uses h1? 

Thank you,
Sameer

**Comment by michael-milette** [comment]
Hi @sameer-ah ,

The GCWeb theme for Moodle software is based on and adapted from the Goverment of Canada's CDTS theme version 4.0.30, a special version of the GCWeb theme created specifically for applications.

If you take a look, you will see that the h2 level heading is clearly correct.
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_30/cdts/appTop/apptop_all-en.shtml

For more information on CDTS GCWeb theme, please visit:
https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html

Best regards,

Michael

**Comment by michael-milette** [comment]
![image](https://user-images.githubusercontent.com/3808579/127439698-4a7c25fa-fe8e-4581-9ebb-2cf790366033.png)

**Comment by michael-milette** [comment]
It is a common misconception that the first heading in a page must be an H1.
