### ISSUE TITLE
Breadcrumbs navigation remove current page

### ISSUE THREAD

**Issue by sameer-ah** [michael-milette/moodle-theme_gcweb#14]
Hi @michael-milette,

In Moodle, breadcrumbs navigation displays current page as a link. Clicking on it does nothings and only reloads current page. For example, if we click on Site Administration from left menu, breadcrumbs navigation is 

![image](https://user-images.githubusercontent.com/36570250/127674490-fd1b2a31-f0aa-4f25-812d-b1b7b84bc1a5.png)

Clicking on Search in breadcrumbs reloads the page.

What about removing current page from breadcrumbs? Please share your thoughts on this change.
I can make CSS change and create a pull request. 

Thank you,
Sameer

**Comment by michael-milette** [comment]
Hi @sameer-ah 

This is the way in which Moodle's breadcrumbs works.

Related information:

**Success Criterion**: WCAG 2.1, 2.4.8: Location.
https://www.w3.org/WAI/WCAG21/Understanding/location.html

**The Intent**: "The intent of this Success Criterion is to provide a way for the user to orient herself within a set of Web pages, a Web site, or a Web application and find related information.". This is the criterion that you need to meet. Everything that comes after it is description, suggestions on how to test and meet the criterion. In WCAG 1.0, you could implement perfectly sound technical solution and still fail the intent. In 2.x, it is all about meeting the intent, regardless of how you achieve this technically.

**Criterion level:** AAA

As this is a level AAA criterion, I believe that the current breadcrumb implementation is sufficient to meet level AA even though the last item in the list is a link. Having it not be a link is more of a nice-to-have.

If you want to pursue this further, my recommendation would be to open a ticket at tracker.moodle.org and push to get it fixed there as this is a core Moodle issue, not a GCWeb theme issue.

**_Did you know?_** In Moodle code, the breadcrumb trail is actually known as a **navbar**. Use this term to help locate relevant functions and classes needed to extend using Moodle relevant renderers. The following documentation may be helpful as a starting point for your efforts:
https://docs.moodle.org/dev/Navigation_API#Navbar

As this is a Moodle core issue, I will close the ticket. However, please feel free to re-open this ticket if you decide to spend time on trying to address this issue from within the theme.

Best regards,

Michael

**Comment by sameer-ah** [comment]
Hi @michael-milette,

Thank you for the detailed information. I will open this issue at tracker.moodle.org to get fixed in core Moodle.

Thank you,
Sameer
