### ISSUE TITLE
Cards using gcweb theme

### ISSUE THREAD

**Issue by sameer-ah** [michael-milette/moodle-theme_gcweb#16]
Hi @michael-milette,

We are trying to add cards to a course. On the course page, after clicking **turn editing on**, _Edit_ -> _Edit Section_. In the editor, following HTML is added
```
<div class="container-fluid mt-4">
    <div class="row">
        <div class="col-auto mb-3 filter employee">
            <div class="card" style="width: 16rem;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">
                        <b>L1. Accessing </b>
                    </h5>
                    <p class="card-text">This shows you how to obtain your&nbsp;key, if you don’t already have it, and how to register on MyHR.This shows you how to obtain your&nbsp;key, if you don’t already have it, and how to register on MyHR.This shows you how to obtain
                        your&nbsp;key, if you don’t already have it, and how to register on MyHR.</p>
                    <a class="btn btn-primary  mt-3" href="/mod/lesson/view.php?id=4">Launch</a>
                </div>
            </div>
        </div>
        <div class="col-auto mb-3 filter employee">
            <div class="card" style="width: 16rem;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">
                        <b>L2. Retrieving </b>
                    </h5>
                    <p class="card-text">This shows you how to obtain your&nbsp;key, if you don’t already have it, and how to register on MyHR.</p>
                    <a class="btn btn-primary  mt-3" href="/mod/lesson/view.php?id=4">Launch</a>
                </div>
            </div>
        </div>
        <div class="col-auto mb-3 filter employee">
            <div class="card" style="width: 16rem;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">
                        <b>L3. Using </b>
                    </h5>
                    <p class="card-text">This shows you how to obtain your&nbsp;key, if you don’t already have it, and how to register on MyHR.</p>
                    <a class="btn btn-info  mt-3" href="/mod/lesson/view.php?id=4">Launch</a>
                </div>
            </div>
        </div>
        <div class="col-auto mb-3 filter employee">
            <div class="card" style="width: 16rem;">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">
                        <b>L4. Outcome </b>
                    </h5>
                    <p class="card-text">This shows you how to obtain your&nbsp;key, if you don’t already have it, and how to register on MyHR.</p>
                    <a class="btn btn-success  mt-3" href="/mod/lesson/view.php?id=4">Launch</a>
                </div>
            </div>
        </div>
    </div>
</div>
```
When using **boost** theme, the above code is rendered as 
![image](https://user-images.githubusercontent.com/36570250/129260332-3517db99-7144-4d93-baa8-25da0078dbf7.png)
But using **gcweb** theme, it is rendered as
![image](https://user-images.githubusercontent.com/36570250/129260412-c9a8f384-ddf1-4269-a0e6-603684bc4d2b.png)
Is **gcweb** theme overwriting default card classes or we need to add additional classes for card to render as in the **boost** theme? 
Just to give you some background, we tried to import a course developed using Moodle boost theme. Is it expected to have issues like this when importing a course developed using boost theme? 

Thank you,
Sameer

**Comment by michael-milette** [comment]
Thanks for bringing this up @sameer-ah . I will look into it when I have a chance.

**Comment by michael-milette** [comment]
With regards to the font size and font family, GCWeb has its own appearance. So yes, it does override the Boost theme in that way. I am just not sure why the width of the cards is different. Will need to investigate.

**Comment by michael-milette** [comment]
The standard base font size in GCWeb for Applications is smaller. 

In GCWeb: 1rem = 10px.
In Boost:    1rem = 16px.

The developer hard coded with card with to 16rem using an inline style. This is why the boxes are smaller.

I suggest that the developer avoid using relative inline styles and perhaps even develop the course using the GCWeb theme.

Closing this ticket as it is not a GCWeb theme issue.
